### ISSUE TITLE
start cannot be in the past error

### ISSUE THREAD

**Issue by insajd** [jmarsik/ad-eurotronic-trv-valvepos#1]
HA 0.104.0
AppDaemon 4
hassio install, though community plugin.
Do you have an idea what's wrong here?

```
2020-01-16 15:28:32.710834 INFO AppDaemon: Adding /config/appdaemon/apps to module import path
2020-01-16 15:28:32.714406 INFO AppDaemon: Adding /config/appdaemon/apps/eurotronic-trv-valvepos to module import path
2020-01-16 15:28:32.728029 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/eurotronic-trv-valvepos/eurotronic-trv-valvepos.py
2020-01-16 15:28:32.773148 INFO AppDaemon: Initializing app eurotronic-trv-valvepos using class EurotronicTRVValvePos from module eurotronic-trv-valvepos
2020-01-16 15:28:32.786968 WARNING eurotronic-trv-valvepos: ------------------------------------------------------------
2020-01-16 15:28:32.788365 WARNING eurotronic-trv-valvepos: Unexpected error running initialize() for eurotronic-trv-valvepos
2020-01-16 15:28:32.789466 WARNING eurotronic-trv-valvepos: ------------------------------------------------------------
2020-01-16 15:28:32.806342 WARNING eurotronic-trv-valvepos: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 145, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 276, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/eurotronic-trv-valvepos/eurotronic-trv-valvepos.py", line 12, in initialize
    self.run_every(self.read_valvepos_from_log, datetime.datetime.now(), int(self.args.get("refresh_seconds", str(5 * 60))))
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 191, in inner_sync_wrapper
    f = run_coroutine_threadsafe(self, coro(self, *args, **kwargs))
  File "/usr/lib/python3.8/site-packages/appdaemon/utils.py", line 285, in run_coroutine_threadsafe
    result = future.result(self.AD.internal_function_timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/site-packages/appdaemon/adapi.py", line 2476, in run_every
    raise ValueError("start cannot be in the past")
ValueError: start cannot be in the past

2020-01-16 15:28:32.807845 WARNING eurotronic-trv-valvepos: ------------------------------------------------------------
```

**Comment by jmarsik** [comment]
Please post your app configuration file. Do you have the `refresh_seconds` parameter there?

**Comment by insajd** [comment]
Here is my config apps.yaml

```
hello_world:
  class: HelloWorld
  module: hello
eurotronic-trv-valvepos:
  module: eurotronic-trv-valvepos
  class: EurotronicTRVValvePos
  ozw_log_path: "/config/OZW_Log.txt"
  look_for_productname: "EUR_SPIRITZ Wall Radiator Thermostat"
  refresh_seconds: 300
check_config:
  module: checkconfig
  class: CheckConfig
  folder_watcher: True
```
I played a bit with and changed line
`self.run_every(self.read_valvepos_from_log, datetime.datetime.now(), int(self.args.get("refresh_seconds", str(5 * 60))))`
to 
`self.run_every(self.read_valvepos_from_log, datetime.datetime.now()+ datetime.timedelta(0,15), int(self.args.get("refresh_seconds", str(5 * 60))))`

Not sure yet whether app works, but error that I had seem to be gone now.
I am runing this on Odroid XU4.

**Comment by insajd** [comment]
All working fine after fix. I suspect my instance is a bit slow, and when something in 
 **run_every**  trying to execute at **datetime.datetime.now()** is failing, because it's already in the past.

**Comment by jmarsik** [comment]
Yes, that looks like to be the cause. I will change it and release a new version. I'm running it on i3 NUC which probably has more power.

**Comment by fergalom** [comment]
Just for info, also running on an i3 NUC and had to implement the fix as per insajd above.
