### ISSUE TITLE
Not working in HA 104?

### ISSUE THREAD

**Issue by fergalom** [jmarsik/ad-eurotronic-trv-valvepos#3]
Just moved to latest HA 104.3 from 102.3

The valvepos app seem to no longer work, getting the following from the appdaemon log:

````2020-01-31 10:04:16.006824 INFO eurotronic-trv-valvepos: Using OZW log file /config/OZW_Log.txt


2020-01-31 10:04:16.026650 WARNING eurotronic-trv-valvepos: ------------------------------------------------------------


2020-01-31 10:04:16.027005 WARNING eurotronic-trv-valvepos: Unexpected error in worker for App eurotronic-trv-valvepos:


2020-01-31 10:04:16.027324 WARNING eurotronic-trv-valvepos: Worker Ags: {'id': '7d7f39a7ddd84dfead2f6131e80e966c', 'name': 'eurotronic-trv-valvepos', 'objectid': 'a5732e5b43af4b80b3df69cdfa9adfff', 'type': 'scheduler', 'function': <bound method EurotronicTRVValvePos.read_valvepos_from_log of <eurotronic-trv-valvepos.EurotronicTRVValvePos object at 0x7fe3d1ad6850>>, 'pin_app': True, 'pin_thread': 0, 'kwargs': {'interval': 300, '__thread_id': 'thread-0'}}


2020-01-31 10:04:16.027626 WARNING eurotronic-trv-valvepos: ------------------------------------------------------------


2020-01-31 10:04:16.028150 WARNING eurotronic-trv-valvepos: Traceback (most recent call last):


  File "/usr/local/lib/python3.8/site-packages/appdaemon/threading.py", line 766, in worker


    funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"]))


  File "/conf/apps/eurotronic-trv-valvepos/eurotronic-trv-valvepos.py", line 29, in read_valvepos_from_log


    if (v["attributes"]["product_name"] == self.args.get("look_for_productname", "EUR_SPIRITZ Wall Radiator Thermostat")):


KeyError: 'product_name'




2020-01-31 10:04:16.028443 WARNING eurotronic-trv-valvepos: ------------------------------------------------------------```

Looks like product_name is not being written to the OZW log anymore?
Or is it working for others on 104?

**Comment by fergalom** [comment]
Just saw this related:
https://github.com/home-assistant/home-assistant/issues/14526#issuecomment-580210442

**Comment by jmarsik** [comment]
HA 0.104 added new functionality for restoring entities on startup. This results in restored unavailable Z-Wave entities with attributes that doesn't contain `product_name` ... I have added simple check and the application is working again.
